[package]
name = "dictionary"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
reqwest = "0.12.22"
scraper = "0.23.1"
tokio = { version = "1.47.0", features = ["full"] }
voca_rs = "1.15.2"
