[package]
name = "explainer-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
explainer = { path = "../explainer-core" }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
